### ISSUE TITLE
Mix task for adding Postgres type is broken

### ISSUE THREAD

**Issue by stevedomin** [lau/calecto#15]
The mix helpers in Ecto have changed to support multiple repos being given to a tasks since [this commit](https://github.com/elixir-lang/ecto/commit/65cc710e05ec8bec5aa7bdf6c911e76ea05ed2ae).

I will try to tackle this issue this week if I find the time.

**Comment by lau** [comment]
:+1:

**Comment by lau** [comment]
fixed in 0.4.5

**Comment by stevedomin** [comment]
Thanks @lau!
