### ISSUE TITLE
Rename Calecto.Model

### ISSUE THREAD

**Issue by lau** [lau/calecto#16]
Now that `Ecto.Model` is no longer used, while `Calecto.Model` still works, it should probably be renamed.
`Calecto.Schema` ?

**Comment by stevedomin** [comment]
:+1: on `Calecto.Schema`

Otherwise `Calecto.Timestamps` since it's the only thing it's doing?

**Comment by lau** [comment]
Good idea with Calecto.Timestamps, because it explains what it does right now. On the other hand Calecto.Schema allows for adding more functionality to it down the road without changing the name. Anyway I just changed it to Calecto.Schema in 0.5.0.

**Comment by stevedomin** [comment]
:+1:
