### ISSUE TITLE
Hex dependency resolution failed

### ISSUE THREAD

**Issue by maxgronlund** [lau/calecto#21]
I'm using
 {:phoenix_ecto, "~> 2.0"}
Maybe you can bump up the deps

**Comment by lau** [comment]
Hi. Which packages are conflicting?

**Comment by maxgronlund** [comment]
{:phoenix_ecto, "~> 2.0"}

**Comment by lau** [comment]
Which package is it conflicting with?

**Comment by lau** [comment]
Hi Max

I tried making a project with these deps:

``` elixir
  defp deps do
    [
     {:calecto, "~> 0.5.2"},
     {:phoenix_ecto, "~> 2.0.0"},
    ]
  end
```

and there were no conflicts. I need more information about which packages are conflicting in order to help.
