### ISSUE TITLE
how to query

### ISSUE THREAD

**Issue by princemaple** [lau/calecto#22]
Hi,

Great package, thanks a lot.

I have a question regarding making queries around datetime related schema

lets say we have this code

``` elixir
from r in Record,
where: r.start >= ^start and r.finish <= ^finish
```

what is the type that `start` and `finish` are supposed to be of? do they have to be the Calecto type that matches the field?

Is `dump/1` called on `start`/`finish`? If so, what do you think about adding another `dump/1` that is equivalent to this [cast](https://github.com/lau/calecto/blob/master/lib/calecto/date_time_utc.ex#L26)?

so we can write something like below and pass in raw datetime strings

``` diff
 def index(conn, %{
   "user_id" => user_id,
   "started_at" => started_at,
   "finished_at" => finished_at
 }) do
   records = Repo.all(
     from r in Record,
     where: r.user_id == ^user_id
-       and r.started_at >= ^cast!(started_at)
+       and r.started_at >= ^started_at
-       and r.finished_at <= ^cast!(finished_at)
+       and r.finished_at <= ^finished_at
   )
   render(conn, "index.json", records: records)
 end
```

**Comment by lau** [comment]
Hi. What type do you have in the schema? `Calecto.DateTimeUTC`? Which version of Calecto and Calendar are you using?

**Comment by princemaple** [comment]
Yes it's using `Calecto.DateTimeUTC`

I'm using Calecto 0.5.2 with Calendar 0.13.2. There is Calendar 0.14 but it shouldn't matter in this case, should it?

**Comment by lau** [comment]
Which version of Ecto do you use?

With Ecto 2.0.0-rc.3 AFAIK it should work directly. E.g. `and r.started_at >= ^started_at`

If you use an Ecto version lower than 2.0.0 Try using the type function: `and r.started_at >= type(^started_at, :datetime)`

**Comment by princemaple** [comment]
Interesting, I am using ecto 2.
And I got an error by doing direct match without casting first.
I'll try again tomorrow and copy the error over.

**Comment by princemaple** [comment]
ok, I forgot to pin it when I tested it with a string literal. somehow I thought when using literals I didn't have to pin. thanks for your help!
