### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by duijf** [lau/calecto#25]
Compiling calecto produces the following warnings: (Ecto 2.0 & Elixir 1.3)

```
warning: function Ecto.Type.blank?/1 is undefined or private
  lib/calecto/date.ex:18
warning: function Ecto.Type.blank?/1 is undefined or private
  lib/calecto/date_time.ex:21
warning: function Ecto.Type.blank?/1 is undefined or private
  lib/calecto/date_time_utc.ex:19
warning: function Ecto.Type.blank?/1 is undefined or private
  lib/calecto/naive_date_time.ex:19
warning: function Ecto.Type.blank?/1 is undefined or private
  lib/calecto/time.ex:19
```

It looks like `Ecto.Type.blank?/1` was removed in Ecto 0.9. I don't know which versions of Ecto you want to support, but if you're open to removing this, I'll send a PR.

**Comment by duijf** [comment]
Here's [the relevant CHANGELOG](https://github.com/elixir-ecto/ecto/blob/v1.0/CHANGELOG.md#v090-2015-03-05). Listed as the second backwards incompatible change.

**Comment by lau** [comment]
Yes please, a PR that removes them would be welcome. The earliest supported Ecto version is currently 1.1.3.
