### ISSUE TITLE
Update the hex package

### ISSUE THREAD

**Issue by vsushkov** [lau/calecto#28]
Hi, it'd be great if you update the hex package. I'm getting elixir warnings. They're fixed in master, but these fixes are not uploaded to hex.pm
<img width="492" alt="screen shot 2016-10-14 at 12 33 08" src="https://cloud.githubusercontent.com/assets/358764/19382837/7eb62620-920a-11e6-9183-2daaf9f760ed.png">

**Comment by chrismccord** [comment]
@lau are there any blockers I can help with to get a new release out with this fixed?

**Comment by lau** [comment]
@vsushkov Thanks. I'll get a new release out and will write a message here once it is done.

**Comment by lau** [comment]
@vsushkov @chrismccord A new release is out now: calecto 0.16.1
