### ISSUE TITLE
Duplicated modules

### ISSUE THREAD

**Issue by ftaebi** [lau/calecto#30]
Hi, I got the following problem when I try to build a release with calecto:

When you include both Ecto and Calecto in your applications list and try to build a release (in my case with distillery) then you get a "Duplicated modules" error because your types have the same names as Ecto's types:

        Duplicated modules:
        'Elixir.Ecto.DataType.Time' specified in ecto and calecto
        'Elixir.Ecto.DataType.NaiveDateTime' specified in ecto and calecto
        'Elixir.Ecto.DataType.DateTime' specified in ecto and calecto
        'Elixir.Ecto.DataType.Date' specified in ecto and calecto

How do you deal with this?

**Comment by mgwidmann** [comment]
I'm getting this as well

**Comment by lau** [comment]
Hi, what version of Ecto are you using?

**Comment by mgwidmann** [comment]
I'm using the release candidate of `2.1.0-rc.4` with elixir 1.3.3. Is this package deprecated now that ecto uses the elixir `Date` and `DateTime` modules? I've removed this package and just used `calendar` and not had any problems.

**Comment by aptinio** [comment]
I've also successfully removed `calecto` and just kept `calendar` with Ecto 2.1. Here's everything I needed to change:

* Replaced `use Calecto.Schema, usec: true` with `@timestamps_opts [type: :utc_datetime, usec: true]`
* Replaced `field :did_at, Calecto.DateTimeUTC` with `field :did_at, :utc_datetime`

**Comment by fpalluel** [comment]
Hello,
I just encountered this issue with elixir 1.4.0 and ECto 2.1.2.
Is the recipe provided by @aptinio the recommended way to go with latest Ecto ?
Thanks !

**Comment by lau** [comment]
Yes Ecto 2.1+ implements some new types that were previously not availible in Ecto itself so Calecto was needed for those. If you use Ecto 2.1+ a lot of now native Ecto types can be used instead of Calecto. E.g. `:utc_datetime` instead of `Calecto.DateTimeUTC`.

So yes it makes sense to replace the Calecto types with an equivalent Ecto type.

In a future release we want to deprecate the types that are now duplicated in Ecto itself.

The `Duplicated modules` is because it was introduced in Ecto 2.1. A new Calecto version that will only work with Ecto 2.1 or higher will remove those definitions and get rid of the errors.

**Comment by mikeni** [comment]
Is this new version of Calecto available?  should I be changing all Calecto.DateTimeUTC to :utc_datetime ?

**Comment by mikeni** [comment]
actually I had to drop this library because of the module conflict,  would there be any reason to continue using the library now that ecto has the new types?

**Comment by lau** [comment]
@mikeni With the new types in Ecto 2.1 the main reason to use the library is `Calecto.DateTime`. The other types now have an equivalent built in to Ecto 2.1.

**Comment by adenisonafifi** [comment]
Is there a timeline for a new Calecto version that works with Ecto 2.1 or higher? I can try digging into a PR.

**Comment by lau** [comment]
@adenisonafifi I hope to have a new version out in the weekend.

**Comment by lau** [comment]
Here is a PR for Ecto 2.1: https://github.com/lau/calecto/pull/37

Testing of the branch and comments are welcome before a new release is made.

cc @adenisonafifi

**Comment by adenisonafifi** [comment]
Testing it out, thank you.

**Comment by kimlai** [comment]
Hi @lau,

Is there anything blocking you from merging your PR and releasing a new version? If so, if there anything we can do to help?

**Comment by lau** [comment]
Closed by https://github.com/lau/calecto/pull/37
Version 0.17.0 is out.
