### ISSUE TITLE
Casting from Calendar.DateTime to DateTimeUTC is not working at all

### ISSUE THREAD

**Issue by sikanhe** [lau/calecto#31]
Calecto fails to convert Calendar.DateTime to Calecto.DateTimeUTC on casting 

to reproduce: 

`Calendar.DateTime.now_utc |> Calecto.DateTimeUTC.cast`

**Comment by lau** [comment]
What version of Calendar, Calecto and Ecto are you using? In newer version you don't need to do that cast.

**Comment by sikanhe** [comment]
This actually happened after I upgraded from 0.6.0 to 0.16.1 this morning, If I just pass the calendar datetime into changeset i get invalid field error. 

I have Calendar as "~> 0.14.0", maybe that's the issue

**Comment by lau** [comment]
Try just removing `|> Calecto.DateTimeUTC.cast` You don't need to cast like that anymore.

**Comment by sikanhe** [comment]
It was my fault, I didn't up the version of Calendar (it was still on 0.14). Just blinded upgraded Calecto without looking at readme. I think it's nice to have that included in the Changelog? I also go there to look at backward incompatible changes. I can help add it there if you want. I didnt know 0.16 Calender was absolutely required.

**Comment by lau** [comment]
Good thing you solved it. This is in the Calecto readme:

> If you use a Calendar version earlier than 0.16, use Calecto version ~> 0.6.1
